import BitcoinBigLogo from "@/components/assets/BitcoinBig";
import TopBar from "@/components/auth/Topbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-hero bg-cover bg-no-repeat w-full h-screen font-sofia-pro">
        <TopBar />
        <div className="flex mt-24 flex-col pb-20">
          <div className="w-full flex justify-center">
            <BitcoinBigLogo />
          </div>

          {children}
        </div>
      </body>
    </html>
  );
}
